terraform {
  required_version = ">= 1.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 3.0"
    }
    azapi = {
      source  = "azure/azapi"
      version = "~> 2.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}

provider "azuread" {}
provider "azapi" {}

data "azuread_client_config" "current" {}

locals {
  # Predict ACA FQDN from the environment domain (avoids circular dependency
  # with the app registration that needs the FQDN for redirect URI).
  aca_fqdn = "${var.app_name}.${azurerm_container_app_environment.main.default_domain}"

  # Token store storage account name: strip hyphens from app name, append "auth"
  easyauth_storage_name = (
    var.easyauth_storage_account_name != ""
    ? var.easyauth_storage_account_name
    : substr("${replace(var.app_name, "-", "")}auth", 0, 24)
  )

  # History storage account name: strip hyphens from app name, append "hist"
  history_storage_name = (
    var.history_storage_account_name != ""
    ? var.history_storage_account_name
    : substr("${replace(var.app_name, "-", "")}hist", 0, 24)
  )
}

# ── Resource Group ────────────────────────────────────────────
resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.location
}

# ── Container Registry ────────────────────────────────────────
resource "azurerm_container_registry" "main" {
  name                = var.acr_name
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku                 = "Basic"
  admin_enabled       = false
}

# ── Log Analytics (required by Container App Environment) ─────
resource "azurerm_log_analytics_workspace" "main" {
  name                = "${var.app_name}-logs"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

# ── VNet (optional — for private endpoint connectivity) ───────
# When enabled, places the ACA environment into a customer-managed VNet.
# All outbound traffic (including Easy Auth sidecar) routes through the
# VNet, enabling private endpoint access to the token store storage.

resource "azurerm_virtual_network" "main" {
  count               = var.enable_vnet ? 1 : 0
  name                = "${var.app_name}-vnet"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  address_space       = [var.vnet_address_space]
}

resource "azurerm_subnet" "aca_infra" {
  count                = var.enable_vnet ? 1 : 0
  name                 = "snet-aca-infra"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main[0].name
  address_prefixes     = [var.aca_subnet_cidr]

  delegation {
    name = "aca"
    service_delegation {
      name    = "Microsoft.App/environments"
      actions = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    }
  }
}

resource "azurerm_subnet" "private_endpoints" {
  count                = var.enable_vnet ? 1 : 0
  name                 = "snet-private-endpoints"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main[0].name
  address_prefixes     = [var.pe_subnet_cidr]
}

# ── Container App Environment ─────────────────────────────────
# When enable_vnet=true, the environment is placed in the customer VNet
# with external ingress (publicly accessible).  The infrastructure subnet
# carries all container + sidecar traffic through the VNet.
resource "azurerm_container_app_environment" "main" {
  name                           = "${var.app_name}-env"
  resource_group_name            = azurerm_resource_group.main.name
  location                       = azurerm_resource_group.main.location
  log_analytics_workspace_id     = azurerm_log_analytics_workspace.main.id
  infrastructure_subnet_id       = var.enable_vnet ? azurerm_subnet.aca_infra[0].id : null
  internal_load_balancer_enabled = var.enable_vnet ? false : null # keep public ingress

  # infrastructure_resource_group_name is auto-generated by Azure for
  # VNet-integrated environments.  Ignoring it prevents Terraform from
  # recreating the environment on every apply.
  lifecycle {
    ignore_changes = [infrastructure_resource_group_name]
  }
}

# ── User-Assigned Managed Identity ────────────────────────────
resource "azurerm_user_assigned_identity" "main" {
  name                = "${var.app_name}-identity"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
}

# Grant AcrPull so the Container App can pull images
resource "azurerm_role_assignment" "acr_pull" {
  scope                = azurerm_container_registry.main.id
  role_definition_name = "AcrPull"
  principal_id         = azurerm_user_assigned_identity.main.principal_id
}

# Grant Azure AI Developer on the AI services resource (for Foundry + OpenAI)
resource "azurerm_role_assignment" "ai_developer" {
  count                = var.ai_services_resource_id != "" ? 1 : 0
  scope                = var.ai_services_resource_id
  role_definition_name = "Azure AI User"
  principal_id         = azurerm_user_assigned_identity.main.principal_id
}

# Grant Contributor on the Fabric capacity resource (for status check + resume)
resource "azurerm_role_assignment" "fabric_capacity_contributor" {
  count                = var.fabric_capacity_resource_id != "" ? 1 : 0
  scope                = var.fabric_capacity_resource_id
  role_definition_name = "Contributor"
  principal_id         = azurerm_user_assigned_identity.main.principal_id
}

# ══════════════════════════════════════════════════════════════
# Easy Auth — Entra ID login + Fabric Data Agent token
# ══════════════════════════════════════════════════════════════
#
# Fabric Data Agent requires **user identity tokens** for data queries.
# MI/SP tokens are rejected at the data layer.
#
# This section creates:
#   1. Entra app registration (Web, with client secret)
#   2. Admin consent grants for Fabric + Graph delegated permissions
#   3. Storage account + blob container for token store
#   4. ACA Easy Auth config via ARM API (azapi)
#
# After apply, ONE manual step remains:
#   - Add the MI to your Fabric workspace as Admin (see post_infra_deploy.sh)

# ── App Registration ──────────────────────────────────────────

resource "azuread_application" "easyauth" {
  count        = var.enable_easy_auth ? 1 : 0
  display_name = "${var.app_name}-easyauth"

  web {
    redirect_uris = [
      "https://${local.aca_fqdn}/.auth/login/aad/callback"
    ]
    implicit_grant {
      id_token_issuance_enabled = true
    }
  }

  # Fabric: DataAgent.Execute.All (delegated)
  required_resource_access {
    resource_app_id = "00000009-0000-0000-c000-000000000000" # Microsoft Fabric
    resource_access {
      id   = "c6756612-6853-4145-a661-90c1d045b2dc" # DataAgent.Execute.All
      type = "Scope"
    }
  }

  # Graph: openid, profile, email, User.Read (delegated)
  required_resource_access {
    resource_app_id = "00000003-0000-0000-c000-000000000000" # Microsoft Graph
    resource_access {
      id   = "37f7f235-527c-4136-accd-4a02d197296e" # openid
      type = "Scope"
    }
    resource_access {
      id   = "14dad69e-099b-42c9-810b-d002981feec1" # profile
      type = "Scope"
    }
    resource_access {
      id   = "64a6cdd6-aab1-4aaf-94b8-3cc8405e90d0" # email
      type = "Scope"
    }
    resource_access {
      id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d" # User.Read
      type = "Scope"
    }
  }

  # Redirect URI is managed by Terraform but requires Application
  # Administrator role to update when the FQDN changes (e.g. VNet migration).
  lifecycle {
    ignore_changes = [web[0].redirect_uris]
  }
}

resource "azuread_service_principal" "easyauth" {
  count                        = var.enable_easy_auth ? 1 : 0
  client_id                    = azuread_application.easyauth[0].client_id
  app_role_assignment_required = true # Only assigned users/groups can authenticate
}

# ── Security Groups ───────────────────────────────────────────
# MAF-App-Users: members can log in to the app.
# MAF-Data-Users: members get Fabric workspace access for Data Agent queries.
# Add users to these groups to onboard them (see deploy/add_user.sh).

resource "azuread_group" "app_users" {
  count            = var.enable_easy_auth ? 1 : 0
  display_name     = "${var.app_name}-App-Users"
  description      = "Members can log in to the ${var.app_name} app"
  security_enabled = true
  owners           = [data.azuread_client_config.current.object_id]
}

resource "azuread_group" "data_users" {
  count            = var.enable_easy_auth ? 1 : 0
  display_name     = "${var.app_name}-Data-Users"
  description      = "Members get Fabric workspace access for Data Agent queries via ${var.app_name}"
  security_enabled = true
  owners           = [data.azuread_client_config.current.object_id]
}

# Assign the App-Users group to the Enterprise Application (Default Access role)
resource "azuread_app_role_assignment" "app_users" {
  count               = var.enable_easy_auth ? 1 : 0
  app_role_id         = "00000000-0000-0000-0000-000000000000" # Default Access
  principal_object_id = azuread_group.app_users[0].object_id
  resource_object_id  = azuread_service_principal.easyauth[0].object_id
}

resource "azuread_application_password" "easyauth" {
  count          = var.enable_easy_auth ? 1 : 0
  application_id = azuread_application.easyauth[0].id
  display_name   = "ACA Easy Auth"
  end_date       = timeadd(plantimestamp(), "17520h") # ~2 years

  lifecycle {
    ignore_changes = [end_date]
  }
}

# ── Admin Consent Grants ──────────────────────────────────────
# These grant delegated permissions on behalf of all users in the tenant.

data "azuread_service_principal" "fabric" {
  count     = var.enable_easy_auth ? 1 : 0
  client_id = "00000009-0000-0000-c000-000000000000"
}

data "azuread_service_principal" "graph" {
  count     = var.enable_easy_auth ? 1 : 0
  client_id = "00000003-0000-0000-c000-000000000000"
}

resource "azuread_service_principal_delegated_permission_grant" "fabric" {
  count                                = var.enable_easy_auth ? 1 : 0
  service_principal_object_id          = azuread_service_principal.easyauth[0].object_id
  resource_service_principal_object_id = data.azuread_service_principal.fabric[0].object_id
  claim_values                         = ["DataAgent.Execute.All"]
}

resource "azuread_service_principal_delegated_permission_grant" "graph" {
  count                                = var.enable_easy_auth ? 1 : 0
  service_principal_object_id          = azuread_service_principal.easyauth[0].object_id
  resource_service_principal_object_id = data.azuread_service_principal.graph[0].object_id
  claim_values                         = ["openid", "profile", "User.Read", "email"]
}

# ── Token Store (blob storage for Easy Auth session tokens) ───
# When VNet is enabled, public access is disabled and the Easy Auth
# sidecar reaches the storage account via a private endpoint within
# the VNet.  Without VNet, public access must remain enabled because
# the sidecar runs on the ACA platform network outside any customer VNet.
#
# Uses azapi instead of azurerm because tenant policy forces
# allowSharedKeyAccess=false, and the azurerm provider requires shared
# key access for its data-plane polling during create/import.

resource "azapi_resource" "tokenstore_account" {
  count     = var.enable_easy_auth ? 1 : 0
  type      = "Microsoft.Storage/storageAccounts@2023-05-01"
  name      = local.easyauth_storage_name
  parent_id = azurerm_resource_group.main.id
  location  = azurerm_resource_group.main.location

  body = {
    kind = "StorageV2"
    sku = {
      name = "Standard_LRS"
    }
    properties = {
      publicNetworkAccess      = var.enable_vnet ? "Disabled" : "Enabled"
      allowSharedKeyAccess     = false
      minimumTlsVersion        = "TLS1_2"
      supportsHttpsTrafficOnly = true
    }
  }
}

resource "azapi_resource" "tokenstore_container" {
  count     = var.enable_easy_auth ? 1 : 0
  type      = "Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01"
  name      = "tokenstore"
  parent_id = "${azapi_resource.tokenstore_account[0].id}/blobServices/default"

  body = {
    properties = {
      publicAccess = "None"
    }
  }
}

resource "azurerm_role_assignment" "tokenstore_blob" {
  count                = var.enable_easy_auth ? 1 : 0
  scope                = azapi_resource.tokenstore_account[0].id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_user_assigned_identity.main.principal_id
}

# ── Token Store Private Endpoint (VNet mode) ──────────────────
# When VNet is enabled, creates a private endpoint so the Easy Auth
# sidecar can reach the token store without public network access.

resource "azurerm_private_endpoint" "tokenstore" {
  count               = var.enable_vnet && var.enable_easy_auth ? 1 : 0
  name                = "${local.easyauth_storage_name}-pe"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  subnet_id           = azurerm_subnet.private_endpoints[0].id

  private_service_connection {
    name                           = "${local.easyauth_storage_name}-psc"
    private_connection_resource_id = azapi_resource.tokenstore_account[0].id
    subresource_names              = ["blob"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [azurerm_private_dns_zone.blob[0].id]
  }
}

resource "azurerm_private_dns_zone" "blob" {
  count               = var.enable_vnet && var.enable_easy_auth ? 1 : 0
  name                = "privatelink.blob.core.windows.net"
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_private_dns_zone_virtual_network_link" "blob" {
  count                 = var.enable_vnet && var.enable_easy_auth ? 1 : 0
  name                  = "${var.app_name}-blob-dns-link"
  resource_group_name   = azurerm_resource_group.main.name
  private_dns_zone_name = azurerm_private_dns_zone.blob[0].name
  virtual_network_id    = azurerm_virtual_network.main[0].id
  registration_enabled  = false
}

# ══════════════════════════════════════════════════════════════
# Persistent History Storage — Azure Blob Storage
# ══════════════════════════════════════════════════════════════
#
# Stores session snapshots and sandbox files so run history survives
# ACA redeploys and restarts.  Uses the same auth pattern as the
# Easy Auth token store (UAMI + DefaultAzureCredential, no shared keys).

resource "azapi_resource" "history_account" {
  count     = var.enable_history_storage ? 1 : 0
  type      = "Microsoft.Storage/storageAccounts@2023-05-01"
  name      = local.history_storage_name
  parent_id = azurerm_resource_group.main.id
  location  = azurerm_resource_group.main.location

  body = {
    kind = "StorageV2"
    sku = {
      name = "Standard_LRS"
    }
    properties = {
      publicNetworkAccess      = var.enable_vnet ? "Disabled" : "Enabled"
      allowSharedKeyAccess     = false
      minimumTlsVersion        = "TLS1_2"
      supportsHttpsTrafficOnly = true
    }
  }
}

resource "azapi_resource" "history_container" {
  count     = var.enable_history_storage ? 1 : 0
  type      = "Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01"
  name      = "history"
  parent_id = "${azapi_resource.history_account[0].id}/blobServices/default"

  body = {
    properties = {
      publicAccess = "None"
    }
  }
}

resource "azurerm_role_assignment" "history_blob" {
  count                = var.enable_history_storage ? 1 : 0
  scope                = azapi_resource.history_account[0].id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_user_assigned_identity.main.principal_id
}

# Lifecycle management: auto-delete history after N days
resource "azurerm_storage_management_policy" "history_lifecycle" {
  count              = var.enable_history_storage && var.history_retention_days > 0 ? 1 : 0
  storage_account_id = azapi_resource.history_account[0].id

  rule {
    name    = "auto-delete-old-history"
    enabled = true
    filters {
      prefix_match = ["history/"]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than    = 30
        delete_after_days_since_modification_greater_than           = var.history_retention_days
      }
    }
  }
}

# Private endpoint for history storage (VNet mode)
resource "azurerm_private_endpoint" "history_storage" {
  count               = var.enable_vnet && var.enable_history_storage ? 1 : 0
  name                = "${local.history_storage_name}-pe"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  subnet_id           = azurerm_subnet.private_endpoints[0].id

  private_service_connection {
    name                           = "${local.history_storage_name}-psc"
    private_connection_resource_id = azapi_resource.history_account[0].id
    subresource_names              = ["blob"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = var.enable_easy_auth ? [azurerm_private_dns_zone.blob[0].id] : [azurerm_private_dns_zone.blob_history[0].id]
  }
}

# When VNet is enabled but Easy Auth is not, we need our own blob DNS zone.
# When both are enabled, reuse the one created for the token store.
resource "azurerm_private_dns_zone" "blob_history" {
  count               = var.enable_vnet && var.enable_history_storage && !var.enable_easy_auth ? 1 : 0
  name                = "privatelink.blob.core.windows.net"
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_private_dns_zone_virtual_network_link" "blob_history" {
  count                 = var.enable_vnet && var.enable_history_storage && !var.enable_easy_auth ? 1 : 0
  name                  = "${var.app_name}-hist-blob-dns-link"
  resource_group_name   = azurerm_resource_group.main.name
  private_dns_zone_name = azurerm_private_dns_zone.blob_history[0].name
  virtual_network_id    = azurerm_virtual_network.main[0].id
  registration_enabled  = false
}

# ── Container App ─────────────────────────────────────────────
# Starts with hello-world image; deploy.sh pushes the real image.

resource "azurerm_container_app" "main" {
  name                         = var.app_name
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = azurerm_resource_group.main.name
  revision_mode                = "Single"

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.main.id]
  }

  registry {
    server   = azurerm_container_registry.main.login_server
    identity = azurerm_user_assigned_identity.main.id
  }

  # Easy Auth client secret (only when auth is enabled)
  dynamic "secret" {
    for_each = var.enable_easy_auth ? [1] : []
    content {
      name  = "microsoft-provider-authentication-secret"
      value = azuread_application_password.easyauth[0].value
    }
  }

  template {
    min_replicas = 1
    max_replicas = 1

    container {
      name   = "app"
      image  = "mcr.microsoft.com/k8se/quickstart:latest"
      cpu    = 1.0
      memory = "2Gi"

      env {
        name  = "PROJECT_ENDPOINT"
        value = var.project_endpoint
      }
      env {
        name  = "AZURE_OPENAI_CHAT_DEPLOYMENT_NAME"
        value = var.azure_openai_chat_deployment_name
      }
      env {
        name  = "AZURE_OPENAI_SUMMARY_DEPLOYMENT_NAME"
        value = var.azure_openai_summary_deployment_name
      }
      env {
        name  = "AZURE_CLIENT_ID"
        value = azurerm_user_assigned_identity.main.client_id
      }
      env {
        name  = "ENABLE_INSTRUMENTATION"
        value = "true"
      }

      # Fabric capacity status check (optional)
      dynamic "env" {
        for_each = var.fabric_capacity_resource_id != "" ? [1] : []
        content {
          name  = "FABRIC_CAPACITY_RESOURCE_ID"
          value = var.fabric_capacity_resource_id
        }
      }

      # Fabric Data Agent MCP — only injected when enabled
      dynamic "env" {
        for_each = var.enable_fabric_data_agent ? [1] : []
        content {
          name  = "FABRIC_DATA_AGENT_MCP_URL"
          value = var.fabric_data_agent_mcp_url
        }
      }

      # Graph Mail notifications — only injected when configured
      dynamic "env" {
        for_each = var.mail_sender_address != "" ? [1] : []
        content {
          name  = "MAIL_SENDER_ADDRESS"
          value = var.mail_sender_address
        }
      }

      # Persistent history storage — only injected when enabled
      dynamic "env" {
        for_each = var.enable_history_storage ? [1] : []
        content {
          name  = "HISTORY_STORAGE_ACCOUNT_URL"
          value = "https://${local.history_storage_name}.blob.core.windows.net"
        }
      }
    }
  }

  ingress {
    external_enabled = true
    target_port      = 3000
    transport        = "auto"

    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
  # Image is managed by deploy.sh / CI — don't let Terraform revert it
  lifecycle {
    ignore_changes = [
      template[0].container[0].image,
    ]
  }
}

# ── ACA Easy Auth Configuration (ARM API) ─────────────────────
# Uses azapi because the azurerm provider doesn't support the full
# auth config (token store with MI, login parameters, etc.).

resource "azapi_resource" "easyauth" {
  count     = var.enable_easy_auth ? 1 : 0
  type      = "Microsoft.App/containerApps/authConfigs@2024-10-02-preview"
  name      = "current"
  parent_id = azurerm_container_app.main.id

  body = {
    properties = {
      platform = {
        enabled = true
      }
      globalValidation = {
        unauthenticatedClientAction = "RedirectToLoginPage"
      }
      identityProviders = {
        azureActiveDirectory = {
          registration = {
            clientId                = azuread_application.easyauth[0].client_id
            clientSecretSettingName = "microsoft-provider-authentication-secret"
            openIdIssuer            = "https://login.microsoftonline.com/${data.azuread_client_config.current.tenant_id}/v2.0"
          }
          validation = {
            allowedAudiences = [
              azuread_application.easyauth[0].client_id,
              "api://${azuread_application.easyauth[0].client_id}"
            ]
          }
          login = {
            loginParameters = [
              "scope=openid profile email offline_access https://api.fabric.microsoft.com/.default"
            ]
          }
        }
      }
      login = {
        tokenStore = {
          enabled = true
          azureBlobStorage = {
            blobContainerUri          = "https://${local.easyauth_storage_name}.blob.core.windows.net/tokenstore"
            managedIdentityResourceId = azurerm_user_assigned_identity.main.id
          }
        }
      }
    }
  }

  depends_on = [
    azapi_resource.tokenstore_container,
    azurerm_role_assignment.tokenstore_blob,
    azuread_service_principal_delegated_permission_grant.fabric,
    azuread_service_principal_delegated_permission_grant.graph,
    # When VNet is enabled, wait for the private endpoint so the sidecar
    # can reach the token store before Easy Auth is configured.
    azurerm_private_endpoint.tokenstore,
  ]
}
